### ISSUE TITLE
1.0.0 and 1.0.2 doesn't compile w/ asset-pipeline 2.3.9?

### ISSUE THREAD

**Issue by jraximus** [dellermann/i18n-asset-pipeline#8]
I seem to be getting an error on startup with either the 1.0.0 or the 1.0.2 version. I'm using asset-pipeline v2.3.9. 

| Error Compilation error: startup failed:
.../plugins/i18n-asset-pipeline-1.0.0/src/groovy/asset/pipeline/i18n/I18nProcessor.groovy: 103: [Static type checking] - Cannot find matching method java.util.Properties#getProperty(java.lang.Object, java.lang.Object). Please check if the declared type is right and if the method exists.
 @ line 103, column 48.
   f (it != '') messages.put it, props.getP
                                 ^

.../plugins/i18n-asset-pipeline-1.0.0/src/groovy/asset/pipeline/i18n/I18nProcessor.groovy: 103: [Static type checking] - Cannot find matching method java.util.LinkedHashMap#put(java.lang.Object, java.lang.Object). Please check if the declared type is right and if the method exists.
 @ line 103, column 31.
                   if (it != '') messages.put it, props.getProperty(it, it)

Any help appreciated,
James.

**Comment by dellermann** [comment]
Fixed in commit f0fd631. Please try the new version 1.0.3 of this plugin.

**Comment by dtamm** [comment]
Hey daniel, though this one is already closed, but i just tried the 1.0.3 Version of the plugin and do get the key/value of the label as key and the same for the value in the map... shall i make a pull request? i already got it fixed (aswell as the not workling win.$L function for me)...

**Comment by dellermann** [comment]
Yes, please send a pull request. Thanks for your work.

**Comment by dtamm** [comment]
Hey Daniel, just commited my pull request! If you need any further work of mine, just ring me up!

**Comment by dtamm** [comment]
Oh and btw, if you accept the pull request, may you publish a new version of the plugin? I would like to use the plugin for my project :) thanks!

**Comment by dellermann** [comment]
Hi Dominik, thanks for your work. I'll write some unit tests for the pre-processor. But for now, I published version 1.0.4 of the plugin.

**Comment by dellermann** [comment]
Hi Dominik, I reverted your pull request because my original code was right. I think you use the i18n-asset-pipeline the wrong way: in a `.i18n` file you have to declare the message keys that should be transferred from `grails-app/i18n/messages*.properties`. In commit c4a8ff6fef3d1315d482dfbf376c369cebf0c70d I implement unit tests for both the pre-processor and the processor.
